# Generated by Django 4.0.3 on 2022-06-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.IntegerField()),
                ('image_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('objects_detected', models.CharField(max_length=200)),
                ('timestamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
            ],
        ),
    ]
