# Generated by Django 4.0.3 on 2022-06-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='id',
        ),
    ]
